"""empty message

Revision ID: 4885e25729ca
Revises: a470470fd45a
Create Date: 2023-08-31 22:52:49.612637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4885e25729ca'
down_revision = 'a470470fd45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('extra_activity',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('academic_achievement',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('nonacademic_achievement',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('accept_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('accept_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('nonacademic_achievement',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('academic_achievement',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('extra_activity',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
