"""empty message

Revision ID: 5564a3eac008
Revises: 5b0be0104a69
Create Date: 2023-08-27 05:15:12.703034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5564a3eac008'
down_revision = '5b0be0104a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('extra_activity', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('academic_prestation', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('nonacademic_prestation', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('accept_status', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('uq_student_nik', type_='unique')
        batch_op.drop_constraint('uq_student_nisn', type_='unique')
        batch_op.drop_column('scores')
        batch_op.drop_column('gender')
        batch_op.drop_column('nisn')
        batch_op.drop_column('nik')
        batch_op.drop_column('presention')
        batch_op.drop_column('birthday')
        batch_op.drop_column('father_name')
        batch_op.drop_column('religion')
        batch_op.drop_column('grading')
        batch_op.drop_column('birthplace')
        batch_op.drop_column('mother_job')
        batch_op.drop_column('mother_education')
        batch_op.drop_column('father_education')
        batch_op.drop_column('address')
        batch_op.drop_column('father_job')
        batch_op.drop_column('mother_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_name', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('father_job', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('father_education', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('mother_education', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('mother_job', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('birthplace', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('grading', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('father_name', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('presention', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('nik', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('nisn', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('scores', sa.TEXT(), nullable=True))
        batch_op.create_unique_constraint('uq_student_nisn', ['nisn'])
        batch_op.create_unique_constraint('uq_student_nik', ['nik'])
        batch_op.drop_column('accept_status')
        batch_op.drop_column('nonacademic_prestation')
        batch_op.drop_column('academic_prestation')
        batch_op.drop_column('extra_activity')
        batch_op.drop_column('score')
        batch_op.drop_column('major')

    # ### end Alembic commands ###
