"""empty message

Revision ID: a470470fd45a
Revises: 8fd8d89016b5
Create Date: 2023-08-31 14:20:46.461518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a470470fd45a'
down_revision = '8fd8d89016b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_achievement', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('nonacademic_achievement', sa.Boolean(), nullable=False))
        batch_op.drop_column('academic_prestation')
        batch_op.drop_column('nonacademic_prestation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nonacademic_prestation', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('academic_prestation', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('nonacademic_achievement')
        batch_op.drop_column('academic_achievement')

    # ### end Alembic commands ###
